### PR TITLE
Write lesson on methods with return types

### PR DESCRIPTION
**Pull request by kcleland0818**
This lesson would come after "Method Parameters" and before "Scope"

### CODE REVIEW

**Review by linda-seiter — APPROVED** [review]
"block party"
block part example from before

instead of hardcoding values like 20, can we return random value?  maybe also pick a random trick (no handlbars, do a wheelie, etc).

**Review by linda-seiter — APPROVED** [review]

**Comment by kcleland0818** [comment]
> "block party" block part example from before
> 
> instead of hardcoding values like 20, can we return random value? maybe also pick a random trick (no handlbars, do a wheelie, etc).

I think for the first time seeing a return value being used, it should be deterministic and not random - it just makes it easier to follow along with the lesson. But the random trick is a good point... if time allows, I'll come back if that's alright?

**Review by developerjaym — APPROVED** [review]

**Comment by linda-seiter** [comment]
> > "block party" block part example from before
> > instead of hardcoding values like 20, can we return random value? maybe also pick a random trick (no handlbars, do a wheelie, etc).
> 
> I think for the first time seeing a return value being used, it should be deterministic and not random - it just makes it easier to follow along with the lesson. But the random trick is a good point... if time allows, I'll come back if that's alright?

Can we at least have the function compute something from a parameter value?  A function that just returns a constant does not seem very useful and students find it hard to understand the value in doing that.

**Comment by kcleland0818** [comment]
> > > "block party" block part example from before
> > > instead of hardcoding values like 20, can we return random value? maybe also pick a random trick (no handlbars, do a wheelie, etc).
> > 
> > 
> > I think for the first time seeing a return value being used, it should be deterministic and not random - it just makes it easier to follow along with the lesson. But the random trick is a good point... if time allows, I'll come back if that's alright?
> 
> Can we at least have the function compute something from a parameter value? A function that just returns a constant does not seem very useful and students find it hard to understand the value in doing that.

Ah I see. It took me a minute to figure out a new example that wasn't too math-y...

**Review by linda-seiter — APPROVED** [review]
The code example right before the "Comprehension Check" has weird indentation.

Thanks for adding the percentInFavor example for returning a value and
updating the discussion, it is really helpful.

**Review by linda-seiter — APPROVED** [review]

**Pull request merged**
